package com.asj.gestionhorarios.controller;

import com.asj.gestionhorarios.model.response.Generic.Response;
import com.asj.gestionhorarios.service.interfaces.ReportService;
import lombok.RequiredArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;

@RestController
@RequestMapping("/api/v1/report")
@RequiredArgsConstructor
public class ReportController {
    private final ReportService reportService;

    @GetMapping("{project_id}/{end_date}")
    public ResponseEntity<Response> findByProjectAndMonth(@RequestParam(value = "isDisabled", required = false, defaultValue = "false") boolean isDisabled, @PathVariable Long project_id, @PathVariable @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate end_date){
        return ResponseEntity.status(HttpStatus.OK).body(new Response(Boolean.TRUE, "Report generated by project and month", reportService.findByProjectAndEndDate(project_id, end_date, isDisabled)));
    }

}
